version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  db:
    image: postgres:11.1-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    container_name: APPNAME
    volumes:
      - RAILSPATH:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
