version: '3'

services:
  db:
    image: postgres:11.1-alpine
  web:
    build: .
    volumes:
      - /Users/accountmac/projects/rentealo:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
